name: build-and-create-release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - ".github/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
      - "CHANGELOG.md"
      - "docs/**"

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Git version
      uses: gittools/actions/gitversion/setup@v3.2.0
      with:
        versionSpec: '6.2.0'
    
    - name: Get version
      uses: gittools/actions/gitversion/execute@v3.2.0
      id: get_version
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish Win x64 exe
      run: dotnet publish -c Release --os win --arch x64 -p:Version=${{ steps.get_version.outputs.AssemblySemFileVer  }}

    - name: Publish Linux x64 exe
      run: dotnet publish -c Release --os linux --arch x64 -p:Version=${{ steps.get_version.outputs.AssemblySemFileVer  }}

    - name: Upload Win build artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-x64-build-v${{ steps.get_version.outputs.AssemblySemFileVer  }}
        path: '**/bin/Release/net*/win-x64/publish/tinycity.exe'
        if-no-files-found: error

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64-build-v${{ steps.get_version.outputs.AssemblySemFileVer  }}
        path: '**/bin/Release/net*/linux-x64/publish/tinycity'
        if-no-files-found: error

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.AssemblySemFileVer  }}
        name: Release v${{ steps.get_version.outputs.AssemblySemFileVer  }}
        draft: false
        prerelease: false
        files: |
            **/bin/Release/net*/win-x64/publish/tinycity.exe
            **/bin/Release/net*/linux-x64/publish/tinycity
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}