# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish exe
      run: dotnet publish -c Release --os win --arch x64

    - name: Upload release as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tinycity.exe
        path: ./bin/Release/net8.0/win-x64/publish/tinycity.exe
